[cmake]
version = "3.15"
cmkr-include = "cmake/cmkr.cmake"

[project]
name = "chall"
languages = ["CXX"]
msvc-runtime = "static"

[options]
RE_UNPP_BUILD_TESTS = false

[target.re-unplayplay]
alias = "unplayplay::lib"
type = "library"
compile-features = ["cxx_std_17"]
compile-definitions = ["NOMINMAX"]
sources = ["src/lib/**.cpp"]
include-directories = ["src/lib/"]
msvc.compile-options = ["/MP"]

[target.re-unplayplay-cli]
type = "executable"
link-libraries = ["unplayplay::lib"]
sources = ["src/bin/**.cpp"]

[fetch-content.GTest]
git = "https://github.com/google/googletest"
tag = "v1.15.2"
condition = "re-unpp-build-tests"

[target.re-unplayplay-tests]
type = "executable"
condition = "re-unpp-build-tests"
sources = ["src/tests/**.cpp"]
include-directories = ["src/tests/"]
link-libraries = ["unplayplay::lib", "GTest::gtest_main"]
