name: Python Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test_python:
    if: '!cancelled()'
    name: ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.11]
    env:
      BUILD_TYPE: ${{ matrix.buildtype }}
    steps:
      - uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install bindings
        run: |
          python3 -m pip install -U .[test]
      - name: Test
        run: pytest src/python-tests/
  publish:
    needs: test_python
    if: '!cancelled()'
    name: Publish to PyPI
    # if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools wheel
      - name: Build source distribution
        run: |
          python3 setup.py sdist
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
